### ISSUE TITLE
Autosave slow/hanging

### ISSUE THREAD

**Issue by newsjunkie247** [internetarchive/wayback-machine-webextension#1016]
I'm not sure if this is related to the bug below but the past 24 hours or so Autosave has been very slow and doesn't seem to complete. Sometimes it does work if initiated afterwards manually. This is on Firefox in Windows.

**Comment by cgorringe** [comment]
Autosave does the same as clicking the "Save Page Now" button manually. Either one can be slow if the servers are too busy. Not much we can do on the extension side to fix it.
