### ISSUE TITLE
Recurring Save count update lag 

### ISSUE THREAD

**Issue by newsjunkie247** [internetarchive/wayback-machine-webextension#1028]
There seems to be a recurring lag in the extension where the saved count doesn't update  for newly saved pages, though somehow manually clicking on the "newest" tab does trigger the save count update, even if it does not yet show the saved page.

**Comment by cgorringe** [comment]
That's odd, as the saved count is usually incremented by 1 right away within the extension. On the website, it may take a while to update as the saving is being processed. It sounds like what is happening is the UI isn't being updated and it could be the simple act of switching tabs and back updates the number.

@newsjunkie247 Could you tell me what browser you're using, what OS, and the version of the extension?

**Comment by cgorringe** [comment]
Hi @newsjunkie247 The browser-specific domain names are only used internally within the Extension, and are not supposed to be used directly in the web browser's address box. The delay and error are expected when used directly.
