### ISSUE TITLE
Extension does not open panel to save/view past versions of website, instead opening welcome webpage

### ISSUE THREAD

**Issue by testlum** [internetarchive/wayback-machine-webextension#1030]
**Describe the bug**
As title.

**To Reproduce**
1. Install extension from Firefox add-ons, click the internet archive icon.
2. Welcome page loads instead of panel to save/view past versions of website.

**Expected behavior**
1. Clicking the internet archive icon should pop up panel to enable saving or viewing of past versions of website.

**Screenshots**
![2024-05-27 10_33_28-Welcome to the Internet Archive's Wayback Machine Extension! — Mozilla Firefox](https://github.com/internetarchive/wayback-machine-webextension/assets/65993546/dbb54f91-9578-4ec5-8e0e-6bfb42aa7304)

**Environment (please complete the following information):**
 - Webextension version: 3.2
 - Browser + version: Firefox
 - OS + version: Windows 11 Home

**Additional context**

**Comment by cgorringe** [comment]
Hi @testlum, the Welcome page is supposed to show up the first time that you install the extension. Did the button show up that says "Accept and Enable", and did you click on that? After selecting that the panel should display when you click on the Internet Archive icon.

<img width="342" alt="accept-and-enable" src="https://github.com/internetarchive/wayback-machine-webextension/assets/604259/5839fbe5-cb2a-4356-b0b8-910410f96008">

**Comment by testlum** [comment]
Hmm, I did not see this popup earlier, nor did it appear after I tried reinstalling the extension. Instead, I see this:

![image](https://github.com/internetarchive/wayback-machine-webextension/assets/65993546/45bdf246-44ef-4992-948c-57d0f3632b3d)

Followed by asking for permission to be used in Private mode. After that, there are no more popups and the bug I described occurs.

**Comment by testlum** [comment]
Not sure
