### ISSUE TITLE
Extension Acts As If Wayback Machine is Down

### ISSUE THREAD

**Issue by Mindrix** [internetarchive/wayback-machine-webextension#1039]
**Describe the bug**
Extension states that the Wayback Machine is Unvaliable despite the fact that I can still save pages via [save page now](https://web.archive.org/save) directly on the Internet Archive website. I am unable to save any pages via the extension.

**Environment (please complete the following information):**
 - Wayback Machine Extension Version 3.2
 - Firefox 127.0.2 (64-bit)
 - Windows 11 
 
**Additional context**
Problem began earlier today at around 11am EST.

**Comment by cgorringe** [comment]
@Mindrix, thanks for your report. I had the same issue earlier this morning. It turns out the servers have been down most of today and are slowly being restored, and they still aren't up and working. I let the team know.

**Comment by Mindrix** [comment]
Servers are fixed now.
