### ISSUE TITLE
Maintaining CodeBase Consistency

### ISSUE THREAD

**Issue by thisisayush** [internetarchive/wayback-machine-webextension#338]
Currently in most of the Javascript files the identifiers (function names, variables, etc) don't follow a standard naming convention, some follow the underscore separated names i.e. `borrow_books` while some follow the CamelCase pattern e.g. makeModal`

Another issue to address in this is Inconsistent Indentation across files. Some files use 4 space Indentation while some are using 2 space Indentation.

There should be a proper naming convention and indentation guidelines and should be added in the contribution guidelines that @MaxReinisch is working on (#325 ).

**Comment by sr6033** [comment]
**ESLint** is already being used in the project. Only a proper guideline is to be mentioned for developers contributing to the project.

**Comment by tanweer919** [comment]
Callback definition is also inconsistent. In some places es6 arrow functions are used while in othe places, traditional javascript functions are used.

**Comment by sr6033** [comment]
Transferring the codebase to ES6 is a different issue altogether, and we need to work on it if is approved by high up @tanweer919.
@thisisayush I agree with your conventions. Seems good and consistent.

**Comment by cheevu-RS** [comment]
@sr6033 I guess, they do want to move on to ES6, from Issue #307's response.

**Comment by YashKumarVerma** [comment]
> @sr6033 Yes ESLint is being used, however, there is a lot of inconsistency in naming conventions. Adding it to Guidelines is something that we can use to set standards to prevent such inconsistencies in the future, however, currently existing codebase needs to be made consistent.
> 
> I suggest the following convention after observing the code (for JS):
> 
> * Using camelCase for functions/methods
> * Using lowecase_underscore for a variable name
> * Using UPPERCASE for Constants

How about using camelCase for the variable names as well ? Won't that be more consistent?

**Comment by thisisayush** [comment]
It'll be, but I suggested the convention according to what was being used majorly in the code.

**Comment by YashKumarVerma** [comment]
@thisisayush  can you have a look at #424.

Also, there's a mixture of both notations in the code. So I was a bit confused regarding it.

**Comment by BisariaUtkarsh** [comment]
> @sr6033 Yes ESLint is being used, however, there is a lot of inconsistency in naming conventions. Adding it to Guidelines is something that we can use to set standards to prevent such inconsistencies in the future, however, currently existing codebase needs to be made consistent.
> 
> I suggest the following convention after observing the code (for JS):
> 
> * Using camelCase for functions/methods
> * Using lowecase_underscore for a variable name
> * Using UPPERCASE for Constants

Hello 

I m looking forward to contribute to Internet Archive (Development of extension) for GSOC 2020. So can I take up this issue and implement the following convention.

Thanks

**Comment by cgorringe** [comment]
I created a Style Guide for review here: #467

**Comment by Chaitanya31612** [comment]
Hi, I would like to work on this one. Can I get assigned for this one?
