### ISSUE TITLE
Clicking on a section in the sitemap, redirects to the homepage

### ISSUE THREAD

**Issue by pranshukharkwal** [internetarchive/wayback-machine-webextension#442]
**Describe the bug**
Upon clicking on any section in the sitemap graph, it is redirecting to the Wayback machine homepage. It is working for some pages but is not working for most of the pages.

**To Reproduce**
1. Go to any site (https://geek-university.com/linux/install-ubuntu/) I tried with this one
2. Click on 'The sitemap option in the extension'
3. Click on any of the section in the green graph

**Expected behavior**
It should redirect to the particular page, in the wayback machine

**Screenshots**
![image](https://user-images.githubusercontent.com/21126219/77258976-30f4b000-6ca4-11ea-9a11-5b3e5e6e35bb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome

**Additional context**
Is this a problem or is this how it is designed to work? Also how is the sitemap button supposed to work? What information is being displayed in the graph?

**Comment by cgorringe** [comment]
It's supposed to link to a particular page in the wayback machine, and not the home page. For now, in the latest development version, it opens the Site Map website instead of drawing it within the extension.
