### ISSUE TITLE
Add Share through LINK sharing option 

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-webextension#453]
## Feature
We can add a LINK Sharing button in the SHARE section.
![Capt](https://user-images.githubusercontent.com/42881874/78423118-dd11a000-7681-11ea-8fd7-8a4ca33b34af.PNG)

**Comment by tikhsuP** [comment]
@anishsarangi @cgorringe  What are your thoughts on this?

**Comment by cgorringe** [comment]
Decided to reopen this due to user feedback.

**Comment by AdityaKG-169** [comment]
Hey! I wish to work on this issue if it is still valid. Thanks

**Comment by cgorringe** [comment]
@AdityaKG-169 Yes, you are welcome to work on this issue! It should be an easy one - good for a first contribution. See notes I wrote above for what to implement.

**Comment by cgorringe** [comment]
Oh I forgot there was already a PR #527 but it's outdated now, so you may be able to use some code from that and apply to the latest code.

**Comment by AdityaKG-169** [comment]
Yeah sure! Thanks.

**Comment by AdityaKG-169** [comment]
Can you please tell me the link that needs to be copied? I am working for the first time on this project, so taking some time to figure things out.

**Comment by AdityaKG-169** [comment]
Hi! Please check the PR

**Comment by cgorringe** [comment]
Thank you @AdityaKG-169 it works great! I'll tweak it a little then merge it.

**Comment by AdityaKG-169** [comment]
Great! I can do the necessary changes if you say so?

**Comment by AdityaKG-169** [comment]
Any updates regarding my PR?
