### ISSUE TITLE
Adding a 'SHARE this extension' button

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-webextension#461]
**Is your feature request related to a problem/ issue? Please describe.**
I have always felt the need to share the extension with my friends, there are many extensions in the Chrome Web Store with the same name and logo, so, I need to copy the link from the webstore and share that. It would be great to have a 'share this extension' button that allows me to share this extension with my friends.

**Describe the solution you'd like**
We can add a SHARE button in the bottom most div with the class of 'row'.

![Capture441](https://user-images.githubusercontent.com/42881874/79515298-e4fc1780-8065-11ea-8eda-eae6172727ca.PNG)

**Comment by shucon** [comment]
@cgorringe is this a valid enhancement you feel should be added? Also, can I work on this as I see no one is assigned as of now?

**Comment by cgorringe** [comment]
Copying the link to clipboard can also be done by clicking on the 2nd (Feedback) icon, which takes you to the Chrome store page, and copying that URL from the address bar. What about links to Wayback extensions for other browsers? I think they should be listed on the About page. While this button is conveniently faster, we must also balance the usage of this last remaining space available with the possibility of wanting another icon here in the future.

**Comment by cgorringe** [comment]
Since we're using that spot now for the Logout button, and we have the extension links in the About page, we'll close this issue now.
