### ISSUE TITLE
Install Prompt on Chrome for Archive Home Page.

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-webextension#505]
I don't know yet if this is viable, but I was thinking wouldn't it be nice if, when visiting archive.org or web.archive.org, the Chrome "Install app?" prompt button would show in the address bar. This would direct the user to install the Chrome Extension.

You can see an example of this while visiting the yahoo.com homepage. It shows up as a plus-inside-circle (+) button next to the star icon in the address bar.

Here are a couple of links with detailed info:
https://developers.google.com/web/fundamentals/app-install-banners/native
https://web.dev/customize-install/

They provide instructions for "native apps" but not sure if it also applies to browser extensions. We'd have to develop this on a test site first, as we don't have direct access to modify the archive.org website.

**Comment by NGTmeaty** [comment]
I believe the install app prompt you would be seeing on something like Yahoo would be for a Progressive Web App, rather than an extension and I don't believe there's an easy way to actually make it install an extension rather than a PWA.

**Comment by AdityaKG-169** [comment]
Hey @cgorringe! I have some suggestions regarding this issue.

The round install icon is for the progressive web apps and not for chrome extensions. 

To fulfill the need for a prompt, I can design a modal that shows up on the side of the webpage and will directly install the extension when allowed. 

Similar to [this](https://i.stack.imgur.com/pKNHI.png) but smaller and on the side of the page.

**Comment by cgorringe** [comment]
@AdityaKG-169 That's a good idea. I'll bring it up with the director.

**Comment by AdityaKG-169** [comment]
Yeah sure. If the team finds it relevant, I would love to work on this task. @cgorringe

**Comment by AdityaKG-169** [comment]
Any updates? @cgorringe

**Comment by cgorringe** [comment]
The browser extension links have been added to all the archive.org pages as shown here, so we no longer need to add another link along the side. I'll likely close this issue.

![screenshot](https://user-images.githubusercontent.com/604259/100733476-1b7f6c00-3383-11eb-965c-7c356ee11405.png)
