### ISSUE TITLE
Port Extension to Safari 14

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-webextension#580]
Since the latest Safari will support these web extensions, let's get this working on Safari!

**Comment by hisaac** [comment]
Hi @cgorringe. I'm a macOS developer, and I'm wanting to learn about Safari Web Extensions. I haven't built one before, but maybe I could help out with this? Anything I could work on?

**Comment by cgorringe** [comment]
Hi @hisaac Thanks for your interest!

Prior to Safari 14, one would create a Safari extension using Swift or ObjC like a macOS app. The one currently on the app store is such a native app, and the source is currently located here (which will be moved in the future): https://github.com/cgorringe/wayback-machine-safari-app

With Safari 14, it now supports the WebExtension standard used in other browsers, but it still involves the additional step of compiling into a native macOS wrapper using XCode. There are also incompatibilities between browsers. One thing that I'm currently working on is to convert from using the `chrome.*` to `browser.*` namespace because `chrome` wasn't working with Safari previously, but I read that it may support it now, so going to test that again. Also working through incompatibilities between Chrome and Firefox.

Here's some more to read:

- Safari Web Extensions: https://developer.apple.com/documentation/safariservices/safari_web_extensions
- Chrome incompatibilities: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities
- WebExtension browser API Polyfill: https://github.com/mozilla/webextension-polyfill

I don't need any help at the moment, but feel free to play around with the code!
There may be some other issues that you're welcome to work on.

**Comment by hisaac** [comment]
Thanks for the info and the resources @cgorringe!

**Comment by cgorringe** [comment]
WWDC 2021 video
Explore Safari Web Extension improvements
https://developer.apple.com/videos/play/wwdc2021/10027

**Comment by cgorringe** [comment]
Port to Safari 14 is mostly finished and working, besides the splash window which will be done soon. 
Requires XCode to compile from source and test for now.

**Steps to Install:**

- Open Safari
  - Develop > Allow Unsigned Extensions (enter your system password)
- Open project `safari/Wayback Machine.xcodeproj` in Xcode. Tap Play button.
- Close splash window (or eventually tap button once I get that working)
- In Safari > Preferences > Extensions tab
  - Check to turn on Extension.
  - Select "Always Allow on Every Website..." button, and confirm, then close Preferences window.
- Archive icon will show in toolbar. Tap that.
- Confirm Agreement on Welcome page.
