### ISSUE TITLE
Add-on does not load when Firefox set to "Never remember history"

### ISSUE THREAD

**Issue by DuncanDHall** [internetarchive/wayback-machine-webextension#674]
**Describe the bug**
Add-on does not appear in tool bar when Firefox has been set to "Never remember history" (in about:preferences)

**To Reproduce**
1. Go to about:preferences in Firefox
2. Set History settings (under Privacy and Security) to "Never remember history"
   (Firefox will require restart)
3. Load Wayback Machine as a temporary plugin (as per [Installing the Latest Build in the README](https://github.com/internetarchive/wayback-machine-webextension/blob/master/README.md#Installing-the-Latest-Build)
4. After step 4 of this guide, the extension icon does not load as promised in the toolbar

**Expected behavior**
Expected the archive icon to load in the toolbar by following the above guide.

**Screenshots**
[screenshot](https://www.dropbox.com/s/bpnnatw2j1ueh0j/Wayback%20Firefox%20Bug.png?dl=0)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser Firefox 81.0.2

**Comment by Purhan** [comment]
Hey there, I believe this is not an issue. When "never remember history" is enabled, firefox is treated as in private mode. From the steps to reproduce you mentioned, one step is missing:

> In "about:addons > Wayback Machine > Manage" allow running in private windows

Once that is done, it appears as expected.

![Screenshot from 2020-10-18 21-22-19](https://user-images.githubusercontent.com/10897423/96373139-1f1ab300-1188-11eb-8aa1-44d2dd59b057.png)

**Comment by DuncanDHall** [comment]
Oh nice! Thanks Purhan.
