### ISSUE TITLE
Option to save outlinks and screenshot

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#686]
The Wayback Machine's official [online form](https://web.archive.org/save) already has the two options '**Save outlinks**' and '**Save screen shot**' (both circled in red):

![image](https://user-images.githubusercontent.com/66422959/100718879-cf6e0f00-33f6-11eb-99be-5cbffbc62dfd.png)

**Proposed solution**
Add two buttons for the options I mentioned above.

**Additional context**
I noticed in this [closed issue](https://github.com/internetarchive/wayback-machine-webextension/issues/600#issue-652008831) that the 3rd ticked box indicates 'Add Tooltips to Outlinks and Screenshot options.' Somehow it isn't implemented yet?

**Comment by cgorringe** [comment]
@Melonadev - If you install the Latest Build from Github, you'll see we included Outlinks and Screenshot checkboxes below the Save Page Now button. See the screenshots on the README. We should update the app stores soon.
