### ISSUE TITLE
Failed to load extension in Edge

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#687]
I followed the instructions on the README to load unpacked in Microsoft Edge 87.0.664.52 (latest version) on Windows 10 version 1909, and this message shows up:

**Error Manifest file is missing or unreadable**
![image](https://user-images.githubusercontent.com/66422959/100747321-db6cc780-341c-11eb-8d5a-53652083be81.png)

**Comment by cgorringe** [comment]
@Melonadev Have you tried loading from the `webextension` subdirectory?

**Comment by Melonadev** [comment]
`webextension` works! Issue's solved.
