### ISSUE TITLE
Show error message when there are no bookmarks to import

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-webextension#688]
**Describe the bug**
I think it would be a good idea to show an error message when, in the Bulk Save window, the user tries to import bookmarks but doesn't has any saved in the browser.

**To Reproduce**
1. Open 'Bulk Save' feature window.
2. Make sure you have no bookmarks saved in the browser.
3. Click on 'Import All Bookmarks' button.

**Expected behavior**
An error message should be displayed.

**Comment by cgorringe** [comment]
Sure we can add an error message. There may be other cases where the browser simply doesn't provide access to bookmarks due to some privacy setting (will have to find out). Feel free to submit a PR if you want!

**Comment by Yashraj1406** [comment]
@cgorringe please assign me this issue, I would like to work on it

**Comment by cgorringe** [comment]
OK @Yashraj1406 you're welcome to work on this issue!

**Comment by Ishan-Saini** [comment]
Hey, @cgorringe @tikhsuP  Is this issue still being worked upon?

**Comment by cgorringe** [comment]
This issue was fixed in PR #707. Thanks @Yashraj1406 !
