### ISSUE TITLE
Add rate limiting for wmAvailabilityCheck in bulk save

### ISSUE THREAD

**Issue by krackers** [internetarchive/wayback-machine-webextension#696]
**Describe the bug**
In bulk save, if you pass in a list of URLs and have "only archive never saved" ticked, it's possible to run into rate-limiting errors from the availability check.

**To Reproduce**
Go to bulk save, paste in a list of ~100 URLs that are already archived, tick the "only archive never saved." In dev tools you will see 429 response which isn't handled properly and causes everything to freeze.

**Expected behavior**
Add rate limiting so this does not happen.

**Screenshots**

**Comment by cgorringe** [comment]
Thanks for testing and catching this bug!

**Comment by sarthakkundra** [comment]
Can anyone tell me how do I access the bulk save feature? This seems like an easy fix but I can't seem to find the feature. Although I found the code

**Comment by krackers** [comment]
@sarthakkundra I don't think the version of the extension published in the chrome store has it yet.

**Comment by sarthakkundra** [comment]
@krackers Thanks for the pointer. Where I can get the dev version from? Also how do I start it from the code? I don't see a `run` , `dev` script etc.

**Comment by anishsarangi** [comment]
Hi @sarthakkundra . Please follow the instruction in https://github.com/internetarchive/wayback-machine-webextension#wayback-machine-web-browser-extension to install the extension in your local machine. You can start with https://github.com/internetarchive/wayback-machine-webextension/blob/master/webextension/index.html which the popup page of the extension.

**Comment by sarthakkundra** [comment]
@anishsarangi thanks for the help. Is there any IRC channel, Slack etc where I can get added to continue the conversation? I have some ideas for the extension I'd like to share.

**Comment by sarthakkundra** [comment]
@anishsarangi I launched the `index.html` file with a live server but it seems to be unresponsive. Any idea what could be going wrong? 
CC :- @cgorringe 


https://user-images.githubusercontent.com/52133994/104223959-538dca80-546a-11eb-9255-60d48cc196ca.mov

**Comment by anishsarangi** [comment]
@sarthakkundra please follow the instructions here https://github.com/internetarchive/wayback-machine-webextension#installing-the-extension to install the extension in your local browser

**Comment by cgorringe** [comment]
@sarthakkundra The extension shouldn't be viewed using a web server, but loaded as an extension from the browser. Simply follow the directions in the README under "Installing the Latest Build"

**Comment by sarthakkundra** [comment]
@cgorringe @anishsarangi  Thanks for the help. I was looking at installing the extension in the docs rather than installing the latest build.  👍🏻

**Comment by sarthakkundra** [comment]
@cgorringe What limit should I set for the number of URLs allowed?

**Comment by anishsarangi** [comment]
@sarthakkundra You can set the limit to 30 for now ! Thank you.

**Comment by krackers** [comment]
Alternatively instead of a fixed limit I think from a user-standpoint it would be better to allow an unbounded size but just ensure that the qps is kept low enough to avoid hitting the rate limit. A limit of 30 seems restrictively low considering that there are many legitimate uses for batch-archiving an entire site directory. If you wanted to be even more considerate of server load you could have the delay between requests be a function of the list size, e.g. `max(2sec, ln(list_size))`

**Comment by anishsarangi** [comment]
Thanks @krackers . I agree to the point. We are thinking of handling this from the server side e.g instead of calling multiple requests in a short time, we can pass all URLs in a single request. Limiting the user while adding url is not a good idea

**Comment by sarthakkundra** [comment]
I can write a delay function. Something along the lines of `setTimeOut`. How does that sound? @krackers @anishsarangi

**Comment by sarthakkundra** [comment]
@krackers Getting this error on unpacking the extension. Did something happen with the latest commit? Seemed to work perfectly fine before.
<img width="1440" alt="Screenshot 2021-01-28 at 12 06 19 AM" src="https://user-images.githubusercontent.com/52133994/106037563-df575600-60fc-11eb-9064-cbd0415b59ba.png">

**Comment by krackers** [comment]
@sarthakkundra No idea I'm not actually involved with internet archive at all. Last commit to `background.js` was 25 days ago so I don't think anything changed there. The code in question seems fine to me since within the scope of the callback `result` should definitely be bound. Maybe step through with a debugger?

**Comment by anishsarangi** [comment]
Hi @sarthakkundra. I tried to replicate this, but did't get such errors. I also didn't find any issue with the last commit.
Which browser / OS are you using ?
Thank you for reporting this. Please create a new issue describing it ! Thank you .

**Comment by sarthakkundra** [comment]
Hi @anishsarangi . I think I missed the notification, sorry for the delayed response. I have opened an issue at #704 . Let me know if anything else is needed. Thanks!

**Comment by cgorringe** [comment]
There's an option in the SPN2 API (web.archive.org/save) which is `if_not_archived_within=<timedelta>` where *timedelta* can be a datetime expression like "3d 5h 20m" or a number of seconds, e.g. "120". If there is a capture within the defined timedelta, SPN2 returns that as a recent capture. The default is 10 min. If we could use a timedelta of *forever* (don't know yet what value to put here) then I think that could be used as a solution instead of calling `wmAvailabilityCheck()` which is causing the rate limiting errors.
