### ISSUE TITLE
Adding continuous Integration 

### ISSUE THREAD

**Issue by sarthakkundra** [internetarchive/wayback-machine-webextension#697]
**Is your feature request related to a problem/ issue? Please describe.**
Add a Github action for continuous integration. The extension has a fairly elaborate set of tests I believe adding a CI action will help make the process of PR review easy for the maintainers.

**Describe the solution you'd like**
Adding a Github action

**Describe alternatives you've considered**
Travis CI or Circle CI

**Additional context**
N/A

I can take this up if you approve it.

**Comment by cgorringe** [comment]
I think it's a good idea. The automated tests only really cover a small fraction of the codebase so PR review might only be slightly improved. I've also got some manual tests that I do that I'm planning to document, which may be suitable to be automated later. I'd say it couldn't hurt!

There is one error that occurs during automated tests ("getUrlByParameter is not defined") but it still reports all tests passing. You can see yourself when running `npm test`. I haven't figured out how to fix it yet and could use some help with that too!

You're welcome to adding the Github action (or provide instructions if you don't have access) and Thanks for your help!

**Comment by sarthakkundra** [comment]
@cgorringe I can make a PR for the action. As far as the failing test is considered I'll take a look on that too.

Apart from that are there any beginner friendly issues that can help me get familiarised with the codebase? I think writing some more tests can do that, if that's something you're interested in.

**Comment by sarthakkundra** [comment]
@cgorringe Can you merge the PR if there are no issues or if there are any do let me know.
