### ISSUE TITLE
Site Map returns a 504

### ISSUE THREAD

**Issue by sarthakkundra** [internetarchive/wayback-machine-webextension#699]
**Describe the bug**
The site map feature seems to error out for websites with a lot of archived data.

**To Reproduce**
1. Go to [facebook](https://www.facebook.com/)
2. Click on the extension
3. Click on Site Map

**Expected behavior**
Either the extension shows a site map or an error message after n seconds stating "it took too long" or something similar

**Screenshots**
<img width="1440" alt="Screenshot 2021-01-08 at 3 19 37 PM" src="https://user-images.githubusercontent.com/52133994/104001088-266cbe00-51c5-11eb-9373-8daa25e90aa2.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 

**Additional context**
I think the feature seems to timeout due to the size of the archive (fails with large size). When I tried the feature on this repo it seemed to work fine.

**Comment by cgorringe** [comment]
I think it does take a long time on large popular websites.
The Site Map is not actually in the scope of this codebase, but thanks for letting us know!
I think it was previously reported here: https://github.com/internetarchive/wayback-radial-tree/issues/34

**Comment by sarthakkundra** [comment]
@cgorringe It's the same issue. Thanks for the redirect.
