### ISSUE TITLE
Specific error message for fact checks

### ISSUE THREAD

**Issue by the-pro** [internetarchive/wayback-machine-webextension#703]
When clicking on fact check button if some network error occurs it still says:
`No fact checks found for the current URL.`
which is inappropriate.
We could add a  different error message for when such problem occurs

**Comment by dwaipayan05** [comment]
Can we add a try catch block to get ahold of the network error ?

**Comment by anishsarangi** [comment]
Thank you @the-pro for reporting this. Please feel free to submit a PR resolving this issue.

**Comment by the-pro** [comment]
Yes sir @anishsarangi . I have done a few changes to the code to get a different message for the network errors.

**Comment by cgorringe** [comment]
Thanks!
