### ISSUE TITLE
Latest master branch clone not getting unpacked

### ISSUE THREAD

**Issue by sarthakkundra** [internetarchive/wayback-machine-webextension#704]
**Describe the bug**
Unpacking the latest clone (master) of the Wayback-machine-webextention in Google Chrome extensions is giving multiple errors in scripts/background.js .

**To Reproduce**
1. Clone the repository.
2. Go to `chrome://extensions/`
3. Switch on developer mode
4. Click on `Load Unpacked`.
5. Select the `webextension` directory inside the root.

**Expected behavior**
Extension to compile successfully. 

**Screenshots**
<img width="1440" alt="Screenshot 2021-02-11 at 3 19 59 AM" src="https://user-images.githubusercontent.com/52133994/107577275-3e968980-6c18-11eb-9724-c6a843b308f7.png">

**Desktop (please complete the following information):**
 - OS: MacOS v10.14.6
 - Browser: Google Chrome
 - Version: 88.0.4324.146

**Additional context**
I'm guessing I'm doing something wrong because the code on master should definitely compile. Although I have worked with the extension before and double checked the local setup steps in the readme.

**Comment by cgorringe** [comment]
Although it works fine on my system, there may still be a bug here.
It looks like there's an issue reading from the Storage API using chrome.storage.local.get()

```
Error handling response: TypeError: Cannot read property 'wm_count_setting' of undefined
Unchecked runtime.lastError: IO error: .../LOCK: Access denied. (ChromeMethodBFE: 15::LockFile::5)

```

Looks like the `event` object is undefined.

Writing this down for future reference.
chrome.storage API:
https://developer.chrome.com/docs/extensions/reference/storage/

**Comment by cgorringe** [comment]
The fix should be to take all calls to `chrome.storage.local.get({ ... }, (result) => {` and check that `result` exists before accessing a property from it. It looks like this check was forgotten in numerous places.
