### ISSUE TITLE
Blacklist for Auto-Save

### ISSUE THREAD

**Issue by s-crypt** [internetarchive/wayback-machine-webextension#709]
**Is your feature request related to a problem/ issue? Please describe.**

- There needs to be a blacklist to exclude auto saving sites. _**Private URLs and searches**_ can spam the WBM.

**Describe the solution you'd like**

- An implemented blacklist that has both defaults (like search engines. There is already a basic list [here](https://github.com/kissarat/never-lose/tree/master/chrome/list) and user added domains to not auto archive.

**Describe alternatives you've considered**

- Besides doing everything manually and/or turning on private mode, there is no other option.

**Additional context**

- It might also be a good idea to not archive the Alexa top 100-500 because they are already pretty much covered by manual archives, as well as pattern matching a url for a search query.

Edit: Some things that should be blacklisted:

- Anything with `search?`, `?s`, `s?`, `?searchterm`, `?search`, `?q`, `?query`, `search.cfm`, `search?q`, `result?`, `?st`, `search.aspx?`,  `*/search/*`, `*.amazon.com/s/`, `search#`, `?f`, `?t`  - used for search terms, can still be manually archived
- Delete anything after `?utm_source` - used for attribution. Remove anything after to get just the pure URL
- Delete anything after `#` - used for document locations

**Comment by cgorringe** [comment]
This is a good point, particularly while using search engines and the `?utm_source` or that one that facebook uses.

**Comment by s-crypt** [comment]
The [ClearURL extension](https://github.com/ClearURLs/Addon/) project actually has a list of regex matches to detect and make clean URLs.
https://docs.clearurls.xyz/latest/specs/rules/
https://rules2.clearurls.xyz/data.minify.json

**Comment by cgorringe** [comment]
@s-crypt Thanks for the info!

**Comment by cgorringe** [comment]
@s-crypt Really appreciate the suggestion and info on ClearURLs! I've created a new feature request at #722 - Thanks!

**Comment by cgorringe** [comment]
Adding some notes on terminology for future reference:
- avoid: black / white.
- use: exclude, block, reject, minus.
- use: include, allow, permit, plus, safe.

"whitelist to exclude auto saving sites" actually sounds like the opposite. Maybe we can call this an "Exclude URL Patterns" list of regex's, or how about "Filtered URL Patterns".

**Comment by s-crypt** [comment]
Sorry, I mixed up blacklist and whitelist when I originally wrote this

**Comment by weirdalsuperfan** [comment]
I WANT THIS!!!

**Comment by weirdalsuperfan** [comment]
Forgot I already posted on this, but just coming back again to see if this feature has been implemented (guess not) and to reiterate that I really want this, for things like gmail and facebook especially.

**Comment by cgorringe** [comment]
Finally implemented this in PR #845 if anyone wants to test it out. I should probably add some more URL patterns to the Default List so I welcome any suggestions!

**Comment by cgorringe** [comment]
Hi @contextnerror, although possible, I'd think it wouldn't be as necessary since you can always explicitly tap Save Page Now. 

We used to have a Bulk Save feature where you could import your bookmarks. This could be an alternative as a bookmark list is like an "include list", although it would take some extra steps. The Bulk Save feature has been temporarily removed but we plan to bring it back in the future.
