### ISSUE TITLE
White empty div at the top when the extension is closed

### ISSUE THREAD

**Issue by jayantchaudhary002** [internetarchive/wayback-machine-webextension#711]
**Describe the bug**
->A white empty div at the top when you open any page using the extension and the press the cross icon on the top right.

**To Reproduce**
1. Go to 'Any website' and open the the website with wayback machine extension.
2. Click on 'cross' at the top right corner.

**Expected behavior**
Solution could be to remove the div completely.

**Screenshots**
![image](https://user-images.githubusercontent.com/56104687/109381178-b219e580-78fe-11eb-8190-a79cd04ca931.png)

**Comment by cgorringe** [comment]
I can confirm this bug. Thanks for the report. Since it's on the website and not part of the extension code, labeling this a "redirect"
