### ISSUE TITLE
Option to allow users to 'pause' and 'resume' operations in Bulk Save

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#731]
Occasionally in Bulk Save, particularly around a hundred URLs into the list, the archival operations seem to slow down, as some URLs are stuck in yellow (or red even) for a very long period of time. There was one time I tried opening up the [Wayback Machine site](https://web.archive.org/save) during the slowdown, and it just returns a 403 error resulting from "Too Many Requests".

White tick in a green icon means 'archived successfully':
![image](https://user-images.githubusercontent.com/66422959/114554535-69916e00-9c99-11eb-914a-ef61315ffca3.png)

Yellow icon means 'in the process of archiving':
![image](https://user-images.githubusercontent.com/66422959/114554641-875ed300-9c99-11eb-9e99-119fcdf1c363.png)

White cross in a red icon means 'archival has not started yet':
![image](https://user-images.githubusercontent.com/66422959/114554785-a9585580-9c99-11eb-8cd8-2a673e1714c4.png)

Currently the last icon (white cross in red) allows the user to click on it to remove the corresponding URL from the added list (before user clicks on 'Start Bulk Save').
I propose 'pause', 'resume', and 'abort' options for URLs with the second icon (yellow) as well. Maybe even automatically pause archiving URLs that gets stuck for 5/10/15 minutes, move on to other URLs, then resume/re-archive these stuck URLs later.

**Comment by cgorringe** [comment]
I'm not sure yet if pausing would work, but there are a lot of URLs getting stuck where they timeout and this needs to be fixed.

**Comment by cgorringe** [comment]
Pause & Continue added
