### ISSUE TITLE
Red cross icon doesn't work when sandwiched between green tick icons

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#732]
As mentioned in #731:

> White tick in a green icon means 'archived successfully':
> ![image](https://user-images.githubusercontent.com/66422959/114554535-69916e00-9c99-11eb-914a-ef61315ffca3.png)
> 
> Yellow icon means 'in the process of archiving':
> ![image](https://user-images.githubusercontent.com/66422959/114554641-875ed300-9c99-11eb-9e99-119fcdf1c363.png)
> 
> White cross in a red icon means 'archival has not started yet':
> ![image](https://user-images.githubusercontent.com/66422959/114554785-a9585580-9c99-11eb-8cd8-2a673e1714c4.png)

> **Currently the last icon (white cross in red) allows the user to click on it to remove the corresponding URL from the added list.**

...but it strangely doesn't work (nothing happens when I press it) when sandwiched between successfully archived URLs:
![image](https://user-images.githubusercontent.com/66422959/114558637-77e18900-9c9d-11eb-81cf-62e1aa62d9de.png)

**Comment by cgorringe** [comment]
Strangely, none of the 'X' icons should take any action when clicked after the save process begins.

**Comment by Melonadev** [comment]
Oops, my bad. Closing this issue now.
