### ISSUE TITLE
'Save only URLs that have never been archived' stops after 50 (or 25) consecutive urls or less

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#741]
Enabling 'Save only URLs that have never been archived' in Bulk Save allows only unarchived links to be archived, while others get skipped over (as indicated by a green-square-with-a-white-dot-in-the-middle logo next to the links)

In cases of more than 50 consecutive already-archived links in the beginning (for example [diem.txt](https://github.com/internetarchive/wayback-machine-webextension/files/6377101/diem.txt)), I expect 'Save only URLs that have never been archived' to be able to skip through all of them.

Instead, it stops once it passed 50 links, and it stays there:

![image](https://user-images.githubusercontent.com/66422959/116085957-eaa52800-a6d1-11eb-8f71-703e414894b1.png)

**Comment by Melonadev** [comment]
Probably related:
> I'm not sure yet if pausing would work, but there are a lot of URLs getting stuck where they timeout and this needs to be fixed.

**Comment by cgorringe** [comment]
Thanks for reporting this!

Also somewhat related to #731

**Comment by cgorringe** [comment]
fixed
