### ISSUE TITLE
Copy Archived Links after Bulk Save

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-webextension#743]
**Is your feature request related to a problem/ issue? Please describe.**

In Bulk Save, we'd like a way to copy the Wayback Machine's URLs of the URLs that were just archived.

**Describe the solution you'd like**

2 Solutions:
1. Add a little button containing a link icon next to each URL, after it's been archived (green), that when clicked will copy a link to the Wayback's version of that saved URL. Include a tooltip when hovered over.
2. Add a button outside the list "Copy Saved Links" (normally dimmed?) will copy a full list of URLs to the Clipboard of the Wayback Machine links to every successfully saved URL. Display a message after selected.

**Comment by Melonadev** [comment]
I'd also like the option 'Copy Unarchived/Unsaved Links' in case the Bulk Save feature stops working and I have to open up a new Bulk Save session/tab to continue archiving the remaining links.
