### ISSUE TITLE
Option to save only URLs that have not been archived for a specific amount of time

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#746]
At the bottom of a Bulk Save window are these two options:

![image](https://user-images.githubusercontent.com/66422959/117282745-ab2bc800-ae97-11eb-9c25-82b8071a3653.png)

'Save only URLs that have never been archived.'
'Save Screenshots.'

I'd like a third option there to '**Save only URLs last archived in** [insert year, month, and date] **or earlier**'.

For example, I know that some of the URLs in my list point to pages last saved in 2011 (which is ten years ago), and it has since been significantly updated. The other links in my list, however, I'm not sure about.

If Bulk Save implements this new option, I'll be able to archive the severely outdated links even though they have already been archived a long time ago, and ignore the ones that's already been saved much more recently.

**Comment by Melonadev** [comment]
In fact, here's a better suggestion I just thought of. Let's change it to:

'Save only URLs last archived in [insert year, month, and date] or earlier'

**Comment by cgorringe** [comment]
Good idea!

**Comment by weirdalsuperfan** [comment]
See also #673
