### ISSUE TITLE
Page not available Page displayed unexpectedly: Firefox

### ISSUE THREAD

**Issue by rahulroy9202** [internetarchive/wayback-machine-webextension#747]
**Describe the bug**
On Firefox it sometimes displays this page not available message on working and available pages.

![image](https://user-images.githubusercontent.com/3462467/118646589-021d8f80-b7fe-11eb-9354-3dba4ae0420c.png)

If you are to check the reviews, it becomes very apparent that a lot of users are facing this issue.
https://addons.mozilla.org/en-US/firefox/addon/wayback-machine_new/reviews/

**To Reproduce**
1. Go back and forward on any page rapidly
2. Sometimes on reload too
3. There is a chance that you will encounter the page not available page.

**Expected behavior**
It should provide enough time for the page to load before considering it as a failed page.
Or at-least give an option to disable this auto detection functionality.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 
 - Version 88

**Comment by anishsarangi** [comment]
Hi @rahulroy9202 . Thank you for reporting this bug. We are facing the same issue in the current version of extension also.
I have created a new issue #748 addressing that.

**Comment by cgorringe** [comment]
We really need to update the old version on the store. The latest version on Github shouldn't have this issue. The bug reported for #748 is related but different issue that only occurs while loading 404 pages within a background tab. Please try out the version on Github in the meantime while we update the version on the Firefox store!

**Comment by rahulroy9202** [comment]
Is there any expected date for publishing the new version to for Firefox? Thank You

**Comment by dougp01** [comment]
Getting a similar response from the Chrome and Brave browsers.

**Comment by cgorringe** [comment]
New version 3.0 just released on Firefox. We now turn off the html-embedded popup by default and you can turn it on in the settings.
