### ISSUE TITLE
Add a legend that explains symbols to Bulk Save

### ISSUE THREAD

**Issue by AlexanderRitter02** [internetarchive/wayback-machine-webextension#757]
**Is your feature request related to a problem/ issue? Please describe.**
_In the Bulk Save window:_ The user is confused by the icons used for marking urls as complete, pending etc.
He may not know their meanings.
This is especially problematic with this specific icon (<img src=https://user-images.githubusercontent.com/42546705/128410242-4e3efe83-cfec-458a-a027-5b5326306107.png height=20></img>), which is not self-explanatory in any way. I can only assume to be "already saved".
In general it is a good idea to have a direct reference explanation visible.

**Describe the solution you'd like**
I suggest adding a legend for the icons like it is used in graphs or maps.
See the following example picture for how I imagine it. Exact positioning, design and wording can vary.
![bulk_save_legend](https://user-images.githubusercontent.com/42546705/128410608-ef1c5464-d6a4-4dd9-8e4b-e6a1d27f030d.png)

**Describe alternatives you've considered**
Adding it to a wiki or the Readme. But I strongly think that documentation is not the right place for this, it should be **directly visible** in the user interface at the relevant action.

**Comment by cgorringe** [comment]
Good idea!
