### ISSUE TITLE
Extension broken after update #758

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#760]
After update #758 (three days ago), both the Wayback Machine Count and Bulk Save functions don't even work.

**Comment by cgorringe** [comment]
Thanks @Melonadev the API server is down today. I've contacted the server folks to get it back up.

**Comment by Melonadev** [comment]
It just happened again!

**Comment by cgorringe** [comment]
Sorry, there was a power outage which caused the servers to go down earlier today.
