### ISSUE TITLE
Bulk Save window crashes

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#766]
Browser: Firefox 92.0 (64-bit)

**Steps to reproduce**
1. Click on 'Bulk Save'. A Bulk Save window will pop up:

![image](https://user-images.githubusercontent.com/66422959/132506603-45708566-3d79-4057-97ad-d6b4efb9af33.png)

2. Wait for a few seconds if needed.
3. The window transforms into this, despite me not having entered any URLs:

![image](https://user-images.githubusercontent.com/66422959/132506152-92105022-339d-4433-8b65-c7a07edf0e8b.png)

**Comment by cgorringe** [comment]
Should be fixed now.
