### ISSUE TITLE
Wikipedia popup text extends outside border

### ISSUE THREAD

**Issue by infojunkie** [internetarchive/wayback-machine-webextension#774]
**Describe the bug**
The text within the popup that's shown upon hovering over the green/black IA icon on Wikipedia, extends outside the boundaries of the popup.

**To Reproduce**
1. Enable the "Wikipedia Resources" option
2. Open https://en.wikipedia.org/wiki/World_War_II and scroll down to References
3. Hover over any green/black IA icon that's injected by the extension
4. Observe that the text within the popup appears cut off because it extends outside the popup borders

**Expected behavior**
The text should not be cut off nor extend outside the popup borders.

**Screenshots**
![Screenshot from 2021-09-21 14-28-26](https://user-images.githubusercontent.com/92977/134255152-592569b7-b926-432d-8b97-4188bddb2f2c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome 93.0.4577.82

**Comment by cgorringe** [comment]
Thanks. I noticed that too but forgot to report it!

**Comment by cgorringe** [comment]
fixed #794
