### ISSUE TITLE
Any alternative for archive.ph?

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#776]
Some websites are manually/automatically excluded from archive.org's Wayback Machine.
https://gizmodo.com/when-the-internet-archive-forgets-1830462131
https://archive.org/post/778/exclusions-from-the-wayback-machine

For example: www.reviewed.com is excluded from Wayback Machine but is archived at **archive.ph**, another archive-service website.

Is there already an existing extension/tool similar to this one, but for **archive.ph**? I'm considering bulk-saving some websites there that might not make their way into Wayback.

**Comment by infojunkie** [comment]
Generally speaking, URLs may be excluded from the Wayback Machine at the request of rights holders.

As for similar tools, you might want to start with something like https://github.com/dessant/web-archives which is read-only, and add to it the ability to submit to other archives.
