### ISSUE TITLE
Disable requirement to log to archive.org account prior to enabling "Save Page Now"

### ISSUE THREAD

**Issue by cstanhope** [internetarchive/wayback-machine-webextension#864]
It appears that with the 3.0 version of the Wayback Machine extension that you must now log in to your archive.org account before the "Save Page Now" button will be enabled. This wasn't the case in prior versions. I don't know the full reasoning behind this change other than I note there are at least a couple of new options (off by default) that would probably require a person to be logged in. One of these is "Save to my Web Archive" and the other I can see is "Email Outlinks". There might be others I'm missing.

I don't ever want to save anything I've archived to my account, and I'm not interested in any of the other personalization features. I'm also one of those people that frequently clears browser data and ends up logged out of everything, so I will be logging in repeatedly to use the "Save Page Now" button, which eliminates the efficiency it would otherwise provide. 

Additionally, I use this browser extension in contexts where I do not wish to log in to my account (e.g. at work). In those contexts, the "Save Page Now" feature is now unusable.

**Describe the solution you'd like**
It would be nice if the "Save Page Now" button was enabled even when logged out if none of the personalization features were enabled. 

Even if this is possible, I admit that this appears to be a UX challenge. Right now the UX is the same for everyone, but if my change could be implemented, the experience for people who have enabled personalization functions will be different from those that haven't. I don't necessarily have a good suggestion to overcome that other than to provide additional context as to why the user must log in. 

**Describe alternatives you've considered**
If this can't be made to work, my work around would be to stop using the extension for saving pages and go back to using the web interface.

**Comment by cgorringe** [comment]
Thanks and we appreciate your feedback! I can see why you may not want to have to log in to use Save Page Now. Unfortunately it's not something that I can change back (at least right now) but I _might_ be able to keep it logged in while clearing the browser's cookies so that you wouldn't have to repeatedly log in. I like to clear my browser cookies too. Seems like a common situation. Thanks for pointing it out! Will see what I can do.

**Comment by cstanhope** [comment]
Great! Thanks! And this may not be the place for this comment, but since I'm here, I'd like to say I really like and appreciate the other recent changes to the extension.

**Comment by MurphysLab** [comment]
> Unfortunately it's not something that I can change back (at least right now)

Would it be possible to make the previous version of the browser extension available separately? 

Some do appreciate the privacy aspect of not having our archiving activity tracked. I hope that this gets changed so that login isn't required.

Also, can anyone here explain why this design **choice** was made?

**Comment by rsaarelm** [comment]
Also hit by this, I'm not interested in making an account and the extension is halfway useless to me now. This feels like a dark pattern feature with no technical justification, since you can still anonymously save pages on the Wayback Machine website end with a curl oneliner just as before.

**Comment by cgorringe** [comment]
Thanks everyone for your input. We got it working now so that you can save without logging in or having to create an account. It's currently in the master branch and will be in the next 3.1 release in the app stores.

**Comment by cstanhope** [comment]
Wow, that's great! Thank you!

**Comment by maxim-sm** [comment]
Just wanted to say thanks a lot for listening to us and changing this! It is highly appreciated.

**Comment by mitar** [comment]
This re-appeared for me. I am unable to archive any website. I get a notification that I have to be logged in to archive any page.

**Comment by cgorringe** [comment]
@mitar It may have been due to the server being down (like it has been today). Would you like to try again?

**Comment by mitar** [comment]
Hm, currently is says "Wayback Machine unavailable" to me. Which is different error messages than the last time, when I reported this issue (and then it was for few days me getting that error, before I decided to report it).
