### ISSUE TITLE
Only offer Wayback Machine if archive.org is reachable

### ISSUE THREAD

**Issue by splch** [internetarchive/wayback-machine-webextension#866]
**Is your feature request related to a problem/ issue? Please describe.**
If I don't have an internet connection, the Wayback Machine will still popup, making it tedious to re-navigate to the goal URL.

**Describe the solution you'd like**
Only offer to show a Wayback archive of a page **if** the archive site is available. If it isn't then the popup wouldn't help.

**Describe alternatives you've considered**
Possibly having a setting that makes this optional. I think it should be enabled by default, but the check wouldn't be difficult with a GET request timeout.

**Comment by cgorringe** [comment]
@splch Could you please provide what web browser you are using, what operating system, and what version of the Wayback Machine extension?

**Comment by splch** [comment]
> @splch Could you please provide what web browser you are using, what operating system, and what version of the Wayback Machine extension?

Absolutely!

| Software | Version |
|----------|---------|
| Chrome   | 98      |
| Wayback  | 1.41.4  |

**Comment by splch** [comment]
I think either the onComplete method will activate on timeout,

https://github.com/internetarchive/wayback-machine-webextension/blob/d8343da36df03151c0241a7863ffaffbd9a66d94/webextension/scripts/background.js#L428

or the banner condition should include some reachable check

https://github.com/internetarchive/wayback-machine-webextension/blob/d8343da36df03151c0241a7863ffaffbd9a66d94/webextension/scripts/background.js#L436

What are your thoughts?

**Comment by cgorringe** [comment]
@splch  - I thought it may be the old one on the store. We've got v3.0 for Chrome in review which will be released real soon that should solve this issue. In the meantime v3.0 has been released already on Firefox and Safari if you'd like to check it out, or you can install the version on Github on Chrome - just follow the directions in the README.

**Comment by splch** [comment]
@cgorringe Ah I'll try the upgraded version out! Thanks so much for your work on this :) Big fan
