### ISSUE TITLE
Show the development icon differently than the release one

### ISSUE THREAD

**Issue by infojunkie** [internetarchive/wayback-machine-webextension#880]
When working on this extension, we sometimes need to keep both the development version AND the latest release present in the toolbar for comparison and bug tracking. It would be great to be able to quickly differentiate between them, e.g. by coloring the dev version icon differently.

**Comment by infojunkie** [comment]
Thanks, that would work

**Comment by infojunkie** [comment]
When the red dot is shown, the icon is white instead of cyan.

**Comment by cgorringe** [comment]
Yes, it's only the main icon, not any that have dots.

**Comment by infojunkie** [comment]
> Yes, it's only the main icon, not any that have dots.

Thanks for confirming - but I think this adds to the confusion, not reduces it.

**Comment by cgorringe** [comment]
It's not like I set out to do it. I have to add more icons to fix it. But I'll see, it may be a quick enough fix.

**Comment by infojunkie** [comment]
Thanks, looking good now!
