### ISSUE TITLE
Why is it required to be logged in to archive a page?

### ISSUE THREAD

**Issue by mitar** [internetarchive/wayback-machine-webextension#888]
Previous version of the extension on Firefox did not require that. Doing archive through website itself also does not require that. Why is this required for the new version of the extension? I understand that it is required to access additional features, but for basic archiving it should work without being logged in also through the extension.

**Comment by cgorringe** [comment]
We are working on getting this to work.

**Comment by cgorringe** [comment]
Thank you, then next version 3.1 will let you archive while logged out.
