### ISSUE TITLE
All settings are being reset randomly

### ISSUE THREAD

**Issue by LeLocTai** [internetarchive/wayback-machine-webextension#890]
Extension settings are being reset to default randomly. My guess is this is the cause:

https://github.com/internetarchive/wayback-machine-webextension/blob/c7dddac4cf72758e75b30d80e980c91567159a03/webextension/scripts/background.js#L387-L388

According to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled, the event is
> Fired when the extension is first installed, when the extension is updated to a new version, and when the browser is updated to a new version.

So settings will be reset after extension or browser update. I can't tell if this is the case because I only use the extension occasionally.

The fix would be to check the details.reason object passed into the callback. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/OnInstalledReason

 

**Environment (please complete the following information):**
 - Webextension version: 3.0
 - Browser + version: Firefox 98.0
 - OS + version: Windows 10

**Comment by cgorringe** [comment]
@LeLocTai Thanks for investigating this! I think we missed this in testing because the settings often get reset when using "Debug Add-ons" in Firefox to load the extension. It's very likely the settings were reset after the browser updated. We'll apply the fix you suggested. (or you can even submit a PR if you want!)

**Comment by LeLocTai** [comment]
I'm tied up this weekend. If someone could take a look, that would be great. Otherwise, I can try to send a PR next weekend.

**Comment by cgorringe** [comment]
@LeLocTai That's not a problem. I'll fix it. Thanks.
