### ISSUE TITLE
Opening the archived copy of a URL without creating a new tab

### ISSUE THREAD

**Issue by el4ctr0n** [internetarchive/wayback-machine-webextension#896]
Dear Wayback Machine Chrome extension developers, can you please make it possible to configure in the settings that when I press "Oldest", the oldest archive of the URL would open in the same tab? 

This feature would be enormously helpful for the situations when you need archived copies of multiple currently open URLs. 

Thank you for considering my request. 
I look forward to your reply.

**Comment by cgorringe** [comment]
Thanks for the suggestion!

We can consider changing the setting for "Show Features In"
( ) Tab ( ) Window ( ) Replace [or something like that...]

**Comment by el4ctr0n** [comment]
> Thanks for the suggestion!
> 
> We can consider changing the setting for "Show Features In" ( ) Tab ( ) Window ( ) Replace [or something like that...]

Can you please add this feature? Thank you for your time.

**Comment by cgorringe** [comment]
Added in v3.1.0.3
