### ISSUE TITLE
Save Page Now is opening 6 tabs instead of 1 when logged out

### ISSUE THREAD

**Issue by anishsarangi** [internetarchive/wayback-machine-webextension#901]
**Describe the bug**
If a user is not logged in and when it try to save a url through the input box in the extension ui, it is opening 6 tabs simultaneously.
**To Reproduce**
1. Go to any URL
2. Click on the extension and make sure that you are logged out
3. Type any url in the extension and click "Save Page Now"
4. You will see 6 tabs opening simultaneously

**Expected behavior**
It should open 1 tab

**Comment by infojunkie** [comment]
> You will see 6 tabs opening simultaneously

I only get 1 tab. Maybe there are more steps to reproduce the bug?

**Comment by anishsarangi** [comment]
@infojunkie Make sure you are logged out and you have typed the url in the input box in the extension

**Comment by infojunkie** [comment]
Thanks! Got it now.
