### ISSUE TITLE
Option to disable notifications and pop up window when saving a page

### ISSUE THREAD

**Issue by LordFlashmeow** [internetarchive/wayback-machine-webextension#902]
I find the notifications for "saving page now" and "successfully saved" annoying to deal with and dismiss, and there's no way to turn them off. 

Similarly, I don't have an interest in seeing what resources are being saved, and closing the pop-up window on every save is a nuisance. 

I think it would be great to have a setting to disable notifications and the details window when saving a page. 

(I run automatic saving for pages older than a year, but sometimes I want to make a more recent snapshot)

**Comment by cgorringe** [comment]
On your 2nd point, the details window should only display when the "Show Resources During Save" setting is turned on, and it's set off initially unless you turn it on. But good point on the 1st. We could add a Setting to turn off all notifications.

**Comment by LordFlashmeow** [comment]
Derp. Don't know how I missed that.

**Comment by snvoid** [comment]
Would really appreciate if there was a setting to turn off notifications, especially ones that use the Windows. I used to use another extension but it is being discontinued when google stops supporting manifest v2 and I really appreciated the simplicity of it. 

This is how that one looked. 

https://chrome.google.com/webstore/detail/save-to-the-wayback-machi/eebpioaailbjojmdbmlpomfgijnlcemk

![image](https://user-images.githubusercontent.com/60519765/162584334-bf48eddf-e8e6-45e3-8c62-6bab3934db66.png)
![image](https://user-images.githubusercontent.com/60519765/162584280-cbb6f2a6-ae8f-4667-8377-3c2cd3b78b54.png)
![image](https://user-images.githubusercontent.com/60519765/162584452-bd5172ae-0565-46b9-997b-a37317115c31.png)

**Comment by snvoid** [comment]
Just was wondering when this updated version will be pushed to the chrome web store? Thanks

**Comment by cgorringe** [comment]
@snvoid Since it's fixed, whenever we push the next version. I don't know yet when that will be. Until then, you could try "Installing the Latest Build from Source" instructions.

**Comment by snvoid** [comment]
> @snvoid Since it's fixed, whenever we push the next version. I don't know yet when that will be. Until then, you could try "Installing the Latest Build from Source" instructions.

Okay thank you! appreciate your quick response :)
