### ISSUE TITLE
Disable popup buttons when 'URL not supported'

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-webextension#912]
We may want to dim or disable the buttons in the popup when "URL not supported" text is displayed, since currently (v.3.0.0.13) when user clicks on a button, none of the buttons do anything, including the social share buttons. Except the SPN button currently flips to "URL not supported" when hovered over, which is fine.

**Comment by VishnuRaghavan** [comment]
Will look into this.

**Comment by VishnuRaghavan** [comment]
I have worked on this enhancement, please check below screenshot. Let me know if any suggestions.

**When URL is not supported** 

![Screenshot 2022-05-06 at 11 18 52 PM](https://user-images.githubusercontent.com/23146562/167203769-0df28bae-55ee-4a1a-8987-c0c33f0f7cc2.png)



**When URL is supported**

![Screenshot 2022-05-06 at 11 20 53 PM](https://user-images.githubusercontent.com/23146562/167203932-8464fa5a-1260-40f9-9a70-c381e0baf16f.png)

**Comment by cgorringe** [comment]
I'd say "Outlinks" & "Screenshot" shouldn't be dimmed.
Also "My Archive" since it doesn't make use of the current URL.
Everything else makes use of the URL so look correct.

**Comment by cgorringe** [comment]
Also test with the Search box, since the current URL would change and thus have to update the buttons dim state.

**Comment by cgorringe** [comment]
Also Thanks for working on this @VishnuRaghavan !

**Comment by VishnuRaghavan** [comment]
@cgorringe  Will work on this.

**Comment by VishnuRaghavan** [comment]
@cgorringe  Hey i have made above mentioned changes, check this PR #943
