### ISSUE TITLE
Make popup buttons accessible using tab key

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-webextension#913]
Currently (v3.0.0.13) some buttons on the popup can't be reached using the tab key, including 'Save Page Now', which might require removing the hover flip. (but hope we can keep the flip.) It would be great if all the buttons and checkboxes can be reached using tab.

**Comment by VishnuRaghavan** [comment]
I have worked on tab navigation. i will create a PR please do check. #943

**Comment by cgorringe** [comment]
Thanks @VishnuRaghavan I will try it out, but the code so far looks great!
