### ISSUE TITLE
When logged out from the site, and logged back in from the site from other account, My Archive redirected me to the previous account

### ISSUE THREAD

**Issue by anishsarangi** [internetarchive/wayback-machine-webextension#937]
**Describe the bug**
When the user logs out from it's account in [archive.org](http://archive.org/) website, logged back in from the site from other account and click on the "My Archive" button, the user name is redirecting to the previous account

**To Reproduce**
1. Log into the [archive.org](http://archive.org/) with one account and click on "My Archive" button.
2. Then logout from archive in the [archive.org](http://archive.org/) website and login with other account.
3. Click on "My Archive" button.
4. This will open the previous account's "my web archive" page.

**Expected behavior**
The user's id should change on changing the account in the website.

**Comment by infojunkie** [comment]
Note that when logging out from the extension in step 2, as opposed to the website, the correct account is opened in step 4.
