### ISSUE TITLE
Add excluded websites on the Wayback Machine to the "Auto Save" exclude urls list

### ISSUE THREAD

**Issue by exurd** [internetarchive/wayback-machine-webextension#944]
**Is your feature request related to a problem/ issue? Please describe.**
It is difficult to know if a URL wasn't saved yet or if the whole website was excluded by the Wayback Machine (Such as [quora.com](https://web.archive.org/web/*/quora.com) or [tomshardware.com](https://web.archive.org/web/*/https://www.tomshardware.com/)). Adding them to the list can help reduce requests that attempt to archive these sites.

**Describe the solution you'd like**
These websites should be inserted into the default list that excludes sites from being auto-archived.

**Describe alternatives you've considered**
You could hardcode the excluded sites into a separate list, so users can't remove these excluded sites. We could also show an icon for these excluded sites (like adding a cross in the red number area) to make it clear that it's not possible to archive these sites.

**Comment by exurd** [comment]
I have found a list curated by the Archive Team, [consisting of 1,697 URLs](https://wiki.archiveteam.org/index.php/List_of_websites_excluded_from_the_Wayback_Machine) (not including [partial exclusions](https://wiki.archiveteam.org/index.php/List_of_websites_excluded_from_the_Wayback_Machine/Partial_exclusions)). It's probably for the best if they were hardcoded into the extension.

**Comment by cgorringe** [comment]
Will have to think about hardcoding such a long list of URLs. But at the very least, the extension shouldn't say that it was successful in saving - it should say instead that it failed!

Thanks for catching this bug.
