### ISSUE TITLE
Auto save page constantly re-save page despite I choose "if not archived with past year"

### ISSUE THREAD

**Issue by fireattack** [internetarchive/wayback-machine-webextension#964]
**Describe the bug**

I set Auto save page on and condition is "if not archived: within past year". Yet, it constantly save the same page (at many as 5 copies just today).

**To Reproduce**
1. Enable Auto Save Page.
2. For "if not archived:", choose "within past year".
3. Open some pages.

**Expected behavior**
It should only archive it at the first sight (assuming not archived by others).

**Screenshots**

As you can see here:
![image](https://user-images.githubusercontent.com/4130991/184740991-bc35a54e-9946-4f4b-a9d3-048474587e07.png)

I'm not going to post the exact URLs for now since it would doxx myself, but it happens on lots of websites. One example is Hacker News' user page: https://news.ycombinator.com/threads?id=XXXX (I'm sure it's saved by me since it's my account and there is zero saves before I enabled this feature).

**Environment (please complete the following information):**
 - Webextension version: 3.1
 - Browser + version: Chrome Version 104.0.5112.81 (Official Build) (64-bit)
 - OS + version: [Windows 10]

**Comment by cgorringe** [comment]
@fireattack Thanks for reporting this bug!
I was able to reproduce it, and will work to fix it.
