### ISSUE TITLE
Allow disabling context menu entry

### ISSUE THREAD

**Issue by contextnerror** [internetarchive/wayback-machine-webextension#982]
**Is your feature request related to a problem/ issue? Please describe.**
Since I only ever use the extension from the toolbar, having an extra entry in the context menu just takes up space.

**Describe the solution you'd like**
Allow users to toggle whether or not the extension is visible in the context menu.

**Describe alternatives you've considered**
I could write a userChrome.css to hide the entry manually, but this is not ideal.

**Additional context**
None.

**Comment by cgorringe** [comment]
Some people do use this feature, so we want to keep it, and we want to not clutter up the Settings with too many options.
Thanks for your input!
