### ISSUE TITLE
Add blue checkmark to Twitter profiles

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-webextension#992]
This is a fun little feature that I read somebody post on Twitter:

https://twitter.com/diegovazquez01/status/1649484383093678080
> Would be nice to have a chrome extension that checks the internet archive api and adds back the blue check just like we have and extension to add back the dislikes on youtube.

Similar to how we insert small icons on Wikipedia pages, if there were a way to check our Twitter archives to see if someone's profile used to have a blue checkmark, create an API that could be called by the extension, then reinsert the icon when coming across their handle on Twitter.

I haven't thought this through entirely yet. Just thought it was a fun idea.

**Comment by ramazansancar** [comment]
> This is a fun little feature that I read somebody post on Twitter:
> 
> https://twitter.com/diegovazquez01/status/1649484383093678080
> 
> > Would be nice to have a chrome extension that checks the internet archive api and adds back the blue check just like we have and extension to add back the dislikes on youtube.
> 
> Similar to how we insert small icons on Wikipedia pages, if there were a way to check our Twitter archives to see if someone's profile used to have a blue checkmark, create an API that could be called by the extension, then reinsert the icon when coming across their handle on Twitter.
> 
> I haven't thought this through entirely yet. Just thought it was a fun idea.

If you could elaborate a little more I'd be happy to help.

**Comment by cgorringe** [comment]
Well, first step is to create a service and API on the Wayback Machine to check the Twitter archives. We'll need some assistance from other engineers on the Wayback team.
